SpaceApi/schema

- 11.json
- 12.json
- 13.json
- 14-draft.json
- 8.json
- 9.json
- README.md
The schema attribute should be provided to all schema files, more information can be found [here](http://json-schema.org/latest/json-schema-core.html#rfc.section.7) and [here](https://spacetelescope.github.io/understanding-json-schema/reference/schema.html)
> adds schema attribute

- 14-draft.json
As Gopher is a fast-growing emerging technology, I find it important that a space can also show his representation in the gopher space on the space API. Now with example and fixed spelling :)
> Add gopher URL

- endpoint/14-draft.json
Since Google+ will be shut down in April of 2019, there's no need to keep it in the API. See https://www.theverge.com/2018/12/10/18134541/google-plus-privacy-api-data-leak-developers
> Remove Google+

- 11.json
- 12.json
- 13.json
- 14-draft.json
- 8.json
- 9.json
- README.md
No changes beside the version number for us:
https://json-schema.org/draft-07/json-hyper-schema-release-notes.html#migrating-from-draft-06
> Raise json-schema version to 7

- 14-draft.json
- CHANGELOG.md
Google+ is discontinued since 2019-04-02.
> Remove google+ field

- 14-draft.json
- CHANGELOG.md
The cache key is not used right now and the same function can already be achieved by using http header (e.g. [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control))
> Remove cache key

- 14-draft.json
- CHANGELOG.md
Right now the issue_report_channel is a bit weird:
E.g.
```json
{
"contact": {
"email": "foo@example.com"
},
"issue_report_channel": [
"issue_email",
"twitter"
]
}
```
Which would be valid but obviously doesn't make any sense.
I would remove it since we don't use it anyways.
> Removes issue report channel

- .gitattributes
Avoids merge conflicts due to multiple additions to the CHANGELOG.
> Use union merge for CHANGELOG

- 14-draft.json
- CHANGELOG.md
This PR adds a new sensor type, `network_traffic`, which enables the sharing of network traffic statistics other than the already present number of active connections.
> Add "network traffic" sensor type

- 14-draft.json
- CHANGELOG.md
This way you can build a spaceapi file that is compatible to multiple versions to make a soft migration to new versions possible.
At least as long you don't need to use fields that exclude each other (e.g. using `hPA` barometer unit in 0.13 vs. `hPa` in 0.14).
Renamed the field so it won't be incompatible to versions 0.13 and lower.
Not sure if the field should still be required, but that's something we can also discuss later.
> Replace api field with api_compatibility

- 14-draft.json
- CHANGELOG.md
In order to cover some use cases that we haven't yet anticipated, it would be great to have a generic "links" section in the schema (as already suggested by @rnestler in #30).
Suggestion:
```json
{
…
"links": [
{
"name": "Door Twitter",
"description": "The Twitter account which tweets our door open status",
"url": "https://twitter.com/foo/bar"
},
{
"name": "Jitsi",
"description": "Our Jitsi instance, public for everybody!",
"url": "https://jitsi.example.org/"
}
]
}
```
The `name` and `url` fields would be required, `description` is optional.
> Add "links" section to v14 schema

- 14-draft.json
- CHANGELOG.md
This way, an endpoint with a barometer sensor can be compatible with
both 0.13 and 0.14. See discussion in #69.
> Barometer sensor: Soft-remove `hPA` unit for compatibility reasons

- 14-draft.json
Mumble specifies its own [`mumble:` URL scheme](https://wiki.mumble.info/wiki/Mumble_URL), and Mumble is used by a lot of spaces, so I think we should add support for this.
> Add "mumble" contact option

- 14-draft.json
See also #58. Spacephone doesn't exist anymore and the other links were
broken.
> Remove spacephone and update spacefed / spacesaml links

- .github/workflows/validate-schema.yml
- 14.json
- 15-draft.json
- CHANGELOG.md
- MIGRATION.md
I've started to write a migration guide for the 0.14 release. 
It's a first draft, feel free to edit!
> Release v14

- CHANGELOG.md
I found the older format quite confusing when trying to systematically implement all changes. The items were not in a logical order, but seemingly random.
Instead, I grouped them by top level key.
> Restructure CHANGELOG, group by top level key

- 15-draft.json
I would go with the spaces website, I've named it according to the SpaceAPI field.
Discussion can be found in [issue 144](https://github.com/SpaceApi/directory/issues/144) and in the [meeting notes](https://github.com/SpaceApi/meeting-notes/blob/master/20200510-telco.md#5-decentralized-directory)
> Add linked_spaces attribute

- 15-draft.json
The lastchange property represents a unix timestamp indicating the time
the sensor value was last updated.
For the wind sensor, I added it at the top object, but it could also be added to the nested object properties.
> Added lastchange property to all sensors. Fixes #95

- 15-draft.json
This applies to `state.lastchange` and `events.timestamp`.
As asked in #97
> Specify that the Unix timestamp is in seconds

- .github/workflows/update-docker-image.yml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
> Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

- 15-draft.json
EDIT: We have a solar panel near our space. So far, spaceapi only allowed for `power_consumption`, but `power_generation` was still missing.
This PR intends to change that.
An example can be found at: https://spaceapi.ccc-p.org/
> Add power_generation sensor

- 15-draft.json
- CHANGELOG.md
- Remove deprecated hPA unit from barometer sensor
- Remove redundant mW unit from power_consumption sensor
- Clean up nonsensical unit descriptions
There are other redundant units, for example temperature in kelvin or fahrenheit (and many others), or wind speed in m/s vs km/h. However, I decided not to touch those for now.
> Clean up units

- 15-draft.json
- CHANGELOG.md
@SpaceApi/core The idea for this PR comes from a discussion at the CCC *Regiowochenende* 2023, and is supposed to serve as a starting point for further discussion.
Apart from hacker- and makerspaces, which have a (more or less) permanent, fixed location in the physical world, there are also other types of groups which cannot be properly represented by the current SpaceAPI schema. Concrete examples of such groups are:
- Regional umbrella associations consisting of multiple hacker- or makerspaces
- Supra-regional associations of people from spaces all over the world
One such regional umbrella association has recently created a dedicated SpaceAPI endpoint where they publish news and calendar feeds for events organized by the umbrella organization. Their endpoint currently contains a …
> Make location optional (Discussion: Extend SpaceAPI to associations without physical meeting locations)

- .github/workflows/update-docker-image.yml
- .github/workflows/validate-formatting.yml
- .github/workflows/validate-schema.yml
All the Github Actions are complaing about Node 16 deprecation in actions/checkout@v2. This bumps them all to the most recent version v4.
> chore: bump actions/checkout to v4

- 15-draft.json
- CHANGELOG.md
Add an ISO-3166 alpha-2 country code to the location object.
Note: One could argue that - since the `location` becomes optional with #106 - the country code can be used for umbrella organizations and spaces without fixed location as well and should be outside of the `location` key. On the other hand, the same thing county for the time zone, so I decided to stick with `location`.
Resolves #74.
> Add country_code to location

- 15-draft.json
- CHANGELOG.md
This key can be used to specify a list of areas that make up your physical location. Each area has a required size (in square meters), and an optional name and description.
Replaces #71. (See discussion in that MR for context.)
> Add areas to location

- 15-draft.json
By adding a field to specify the SpaceAPI endpoints of other spaces self discovery of the spaces in the SpaceAPI network becomes possible. This change would eventually allow for a SpaceAPI that is functional without the central directory.
If the endpoint field is filled out then the URL field of the linked space should be left absent as the url can instead be read from the spaces own SpaceAPI endpoint. Because of this I've made the URL endpoint optional.
> Add endpoind field to linked_spaces, rename url field to website

- 15-draft.json
- CHANGELOG.md
This change makes the `lat` and `lon` fields optional (see discussion in #112), but adds some validation logic:
- The `location` fields needs at least one property
- If `lat` is specified, then `lon` is required as well (and vice versa)
This means that `"location": {},` is not valid (at least 1 property required), neither is `"location": {"lat": 1.23}` (both lat and lon) must be specified). But `"location": {"timezone": "Antarctica/Palmer"}` is valid.
Logic is based on the latest [JSON Schema validation draft](https://json-schema.org/draft/2020-12/json-schema-validation#name-validation-keywords-for-obj). I don't know whether there is significant support in tooling for these fields.
Fixes #112
> Location: Make lat/lon optional, but add more validation logic

- 15.json
- CHANGELOG.md
We recently deployed a CO2 sensor and noticed, that there is no sensor for it available within the spaceapi json schema. Therefore I propose to add an CO2/carbondioxide sensor to it :) I assumed, that it can be added to the v15 draft? I just copied the temperature sensor section and adjusted it to fit CO2.
As of now, I found three spaces, that already have CO2 sensor data published. Apparently, all three use different names for them:
- CCC Darmstadt: `co2`
- FabLab Nürnberg: `ext_co2`
- Nerdberg: `carbondioxide`
I just took `carbondioxide` but `co2` should be fine too.
/CC @poschi3
> Add CO2 sensor

- 16-draft.json
- CHANGELOG.md
Yes, some spaces use Telegram ;-). This adds a new field for Telegram chats.
Not sure if it's good to provide an URL to a Telegram channel that does not exist and could be registered by someone... Maybe the example should be removed?
Best,
Mänu
> Added new contact field for Telegram chats

- 16-draft.json
This allows to test the validator, while making sure that we do not have an outdated version of the spec in the validator library once the next version gets released.
> Use 16-draft as the version identifier of the next version

- .github/workflows/update-docker-image.yml
For some reasons, the first commit did not trigger a workflow run like e.g. in the website repository, so there is no action run and published container image to verify. I was unable to figure out what causes the different behavior in this repo.
However, the changes are pretty much straight-forward, and more or less the same as in e.g. the website repo.
> Migrate from Docker Hub to GHCR

- 13.json
- 14.json
- 15.json
- 16-draft.json
While working on [Simple SpaceAPI](https://github.com/He4eT/simple-spaceapi),  
I noticed that the link in the "radiation sensors" section was outdated.  
I replaced it with a new one — hopefully it's the correct one.
> Radiation sensors link

- 16-draft.json
- CHANGELOG.md
After #120 was merged, it makes sense to add a way to contact the keymasters via Telegram as well.
> Add 'telegram' contact field for keymasters
